apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./ks.yaml
  - ./ns.yaml
  - ./rabbitmq/helmrelease.yaml
  - ./rabbitmq/secrets.yaml
  - ./statsd-exporter/helmrelease.yaml
  - ./app/helmrelease.yaml
  - ./app/httproute.yaml
