apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ${APP}
  namespace: ${NAMESPACE}
spec:
  chart:
    spec:
      chart: app-template
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.2.1
  interval: 1m0s
  values:
    controllers:
      main:
        strategy: Recreate
        containers:
          main:
            image:
              repository: ghcr.io/linuxserver-labs/prarr
              tag: lidarr-plugins-3.1.2.4913
              pullPolicy: IfNotPresent
      lidarr-similar:
        strategy: Recreate
        containers:
          main:
            image:
              repository: ghcr.io/drachenhort/lidarr-similar
              tag: 0.4.1
              pullPolicy: IfNotPresent
            env:
              DEEZER_ENABLED: true
              LISTENBRAINZ_ENABLED: true
              DISCOGS_ENABLED: true
              LIDARR_ROOT_FOLDER: "/media/imports/Music/original"
              LIDARR_QUALITY_PROFILE_ID: 2
              LIDARR_METADATA_PROFILE_ID: 1
              LIDARR_URL: "http://lidarr-main:8686"
              LASTFM_API_KEY:
                valueFrom:
                  secretKeyRef:
                    name: lastfm-api-key
                    key: api-key
              LASTFM_USERNAME:
                valueFrom:
                  secretKeyRef:
                    name: lastfm-api-key
                    key: lastfm-username
              LIDARR_API_KEY:
                valueFrom:
                  secretKeyRef:
                    name: lidarr-api-key
                    key: api-key
              DISCOGS_TOKEN:
                valueFrom:
                  secretKeyRef:
                    name: discogs-personal-access-token
                    key: token
    service:
      main:
        controller: main
        ports:
          http:
            port: 8686
      lidarr-similar:
        controller: lidarr-similar
        ports:
          http:
            port: 8000
    persistence:
      data:
        storageClass: "longhorn"
        accessMode: ReadWriteOnce
        size: 4Gi
        advancedMounts:
          main:
            main:
              - path: /config
      music:
        existingClaim: lidarr-media-pvc
        globalMounts:
          - path: /media
      lidarr-similar:
        storageClass: "longhorn"
        accessMode: ReadWriteOnce
        size: 1Gi
        advancedMounts:
          lidarr-similar:
            main:
              - path: /data
