apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lidarr-api-key
  namespace: lidarr
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: lidarr-api-key
  data:
    - secretKey: api-key
      remoteRef:
        key: media/lidarr/api-key
        property: api-key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lastfm-api-key
  namespace: lidarr
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: lastfm-api-key
  data:
    - secretKey: api-key
      remoteRef:
        key: media/lidarr/lidarr-similar/lastfm-api-key
        property: api-key
    - secretKey: shared-secret
      remoteRef:
        key: media/lidarr/lidarr-similar/lastfm-api-key
        property: shared-secret
    - secretKey: lastfm-username
      remoteRef:
        key: media/lidarr/lidarr-similar/lastfm-api-key
        property: lastfm-username
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: discogs-personal-access-token
  namespace: lidarr
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: discogs-personal-access-token
  data:
    - secretKey: token
      remoteRef:
        key: media/lidarr/lidarr-similar/discogs-personal-access-token
        property: token
