apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-ngx-nsfiles-consume-pvc
  namespace: paperless-ngx
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: paperless-ngx-nsfiles-consume-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-ngx-nsfiles-media-pvc
  namespace: paperless-ngx
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: paperless-ngx-nsfiles-media-pv
