apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-ngx-postgres-auth
  namespace: paperless-ngx
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: paperless-ngx-postgres-auth
  data:
    - secretKey: username
      remoteRef:
        key: paperless-ngx/postgres-auth
        property: username
    - secretKey: password
      remoteRef:
        key: paperless-ngx/postgres-auth
        property: password
