apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  chart:
    spec:
      chart: app-template
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.2.1
  interval: 1m0s
  values:
    controllers:
      main:
        strategy: Recreate

        containers:
          main:
            image:
              repository: vaultwarden/server
              tag: 1.35.8
              pullPolicy: IfNotPresent
            env:
              DOMAIN: "https://vaultwarden.artichoke.cc"
              ADMIN_TOKEN:
                valueFrom:
                  secretKeyRef:
                    name: vaultwarden-admin-token
                    key: token
              DATA_FOLDER: "config"
              EXPERIMENTAL_CLIENT_FEATURE_FLAGS: "fido2-vault-credentials,ssh-key-vault-item,ssh-agent"
              DATABASE_URL:
                valueFrom:
                  secretKeyRef:
                    name: vaultwarden-postgres-auth
                    key: url
              SSO_ENABLED: "true"
              SSO_AUTHORITY: "https://auth.artichoke.cc/application/o/vaultwarden/"
              SSO_CLIENT_ID:
                valueFrom:
                  secretKeyRef:
                    name: vaultwarden-oidc-auth
                    key: client-id
              SSO_CLIENT_SECRET:
                valueFrom:
                  secretKeyRef:
                    name: vaultwarden-oidc-auth
                    key: client-secret
              SSO_SCOPES: "email profile offline_access"
              SSO_ALLOW_UNKNOWN_EMAIL_VERIFICATION: "false"
              SSO_CLIENT_CACHE_EXPIRATION: "0"
              SSO_ONLY: "false"
              SSO_SIGNUPS_MATCH_EMAIL: "true"

    service:
      main:
        controller: main
        ports:
          http:
            port: 80

    persistence:
      config:
        storageClass: "longhorn"
        accessMode: ReadWriteOnce
        size: 1Gi
        globalMounts:
          - path: /config
