apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./ks.yaml
  - ./app/pv.yaml
  - ./app/pvc.yaml
  - ./app/secrets.yaml
  - ./app/helmrelease.yaml
  - ./app/httproute.yaml

configMapGenerator:
  - name: slskd-config
    files:
      - ./app/config/slskd.yml
    options:
      disableNameSuffixHash: true
